### PR TITLE
Solved issue #1

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**

### CODE REVIEW

**Comment by arin2002** [comment]
add in folder python

**Comment by arin2002** [comment]
YOU HAVENT MADE A FOLDER

**Comment by akhilender-bongirwar** [comment]
> YOU HAVENT MADE A FOLDER

I am not able to make a folder.

**Comment by akhilender-bongirwar** [comment]
I think you have to make a folder named Python then I can add my file in it

**Comment by arin2002** [comment]
Ok let me do it for you....because you don't know who to make

**Comment by arin2002** [comment]
add now

**Comment by akhilender-bongirwar** [comment]
> add now

Added. Please check.

**Pull request closed without merging**
